### ISSUE TITLE
Introduce the configuration file

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/kwja#129]
## What

It would be nice to have a configuration file that can specify the location of the model files, the default device to use, etc.

## How to implement

Put this kind of file in `$XDG_CONFIG_HOME/kwja`.

```yaml
# $XDG_CONFIG_HOME/kwja/config.yaml
model_path: null
model_size: base
device: gpu
typo_batch_size: 1
char_batch_size: 1
word_batch_size: 1
discourse: true
```
